/**
 * Even Fibonacci Numbers
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequene whose values do not exceed four million, find the sum of the even-valued terms
 * 
 * @author seanmr
 */

let ceiling = 4000000;
let total = 0;

// Calculates the sum of even fibonacci sequence values up to ceiling
function calcEvenFibTermsSum(current_value, previous_value) {  
    // Generate the next term
    let next_value = current_value + previous_value;

    // Add next value to total and find next sequence if ceiling not exceeded
    return next_value > ceiling ? total : (() => {(next_value % 2 == 0) && (total += next_value); return calcEvenFibTermsSum(next_value, current_value)})();
  }

console.log(calcEvenFibTermsSum(1, 0));